MODEL: ExtraNet
EPOCHS: 150
SCALE: 2
BATCH_SIZE: 1
CROP_SIZE: 256
NUMBER_WORKERS: 8
LEARNING_RATE: 0.001
CRITERION: L1
OPTIMIZER:
  NAME: Adam
  BETA1: 0.9
  BETA2: 0.99
SCHEDULER:
  NAME: Cosine
  MIN_LEARNING_RATE: 1.0e-06
  START_DECAY_EPOCH: 20
TRAIN_DATASET: dataset/DIV2K/train
VAL_DATASET: dataset/DIV2K/val
